<?php
/**
 * Fact Check cards — official guide content. Used by admin/seed_fact_cards.php
 * Public fact-check.html uses js/fact-check-data.js (same content, no API).
 */
return [
  ['category' => 'culture_history', 'question' => 'Who designed the national flag?', 'answer' => 'Mrs. Theodosia Salome Okoh.', 'keywords' => 'flag designer theodosia okoh'],
  ['category' => 'culture_history', 'question' => 'Why is Ghana a motherland?', 'answer' => 'First country in sub-Saharan Africa to gain independence, supported and welcomed African freedom and Pan-African movements.', 'keywords' => 'motherland independence pan-african'],
  ['category' => 'culture_history', 'question' => 'On what dates did Ghana independence and become a republic?', 'answer' => 'March 6, 1957 and July 1, 1960 respectively.', 'keywords' => 'independence republic march july 1957 1960'],
  ['category' => 'culture_history', 'question' => 'What do the colors in the national flag symbolize?', 'answer' => "Red: Blood of the people who fought and died for Ghana's independence.\nGold: Ghana's natural wealth and minerals.\nGreen: Ghana's forests, land, and agriculture.\nBlack Star: African freedom, unity, and independence.", 'keywords' => 'flag colors red gold green black star symbolism'],
  ['category' => 'culture_history', 'question' => "What animal and writing appear on Ghana's Coat of Arms?", 'answer' => 'Two eagles, a lion for Commonwealth ties, and the motto "Freedom and Justice".', 'keywords' => 'coat of arms eagles lion freedom justice'],
  ['category' => 'culture_history', 'question' => 'Who wrote the lyrics to the National Anthem and who composed the song?', 'answer' => 'Dr. Michael Kwame Gbordzoe wrote lyrics and Philip Gbeho composed the song.', 'keywords' => 'national anthem gbordzoe gbeho lyrics composer'],
  ['category' => 'culture_history', 'question' => "After how many days is a baby's outdooring ceremony held?", 'answer' => '8 days after birth.', 'keywords' => 'outdooring baby naming 8 days'],
  ['category' => 'general_knowledge', 'question' => 'How would you explain CHALE to a foreigner?', 'answer' => 'Friend/bro.', 'keywords' => 'chale slang friend bro'],
  ['category' => 'general_knowledge', 'question' => 'What is the burnt layer of rice at the bottom of the pot called?', 'answer' => 'Kanzo, 3moase.', 'keywords' => 'rice kanzo 3moase burnt bottom pot'],
  ['category' => 'general_knowledge', 'question' => 'Statutory public holidays in Ghana and the months.', 'answer' => "JANUARY: New Year's Day, Constitution Day.\nMARCH: Independence Day.\nAPRIL: Good Friday, Easter Monday.\nMAY: Labour Day (Worker's Day).\nJULY: Republic Day.\nSEPTEMBER: Founder's Day.\nDECEMBER: Farmer's Day, Christmas Day, Boxing Day.\n\nNB: There are no fixed dates for the Eid-Ul-Fitr, Shaqq Day and Eid-Ul-Adha because they are movable feasts. The dates for their observation are provided by the Office of the Chief Imam in the course of the year.", 'keywords' => 'holidays public statutory independence christmas eid'],
  ['category' => 'movies', 'question' => 'Spell the name of the Ghanaian movie industry.', 'answer' => 'Ghallywood.', 'keywords' => 'ghallywood movies film industry'],
  ['category' => 'places', 'question' => 'Which 3 african countries does Ghana share borders with?', 'answer' => 'Burkina Faso(North), Ivory Coast(West), Togo(East).', 'keywords' => 'borders burkina faso ivory coast togo'],
  ['category' => 'places', 'question' => 'Regions and its Capitals.', 'answer' => 'Ahafo Region: Goaso, Ashanti Region: Kumasi, Bono Region: Sunyani, Bono East Region: Techiman, Central Region: Cape Coast, Eastern Region: Koforidua, Greater Accra Region: Accra, North East Region: Nalerigu, Northern Region: Tamale, Oti Region: Dambai, Savannah Region: Damongo, Upper East Region: Bolgatanga, Upper West Region: Wa, Volta Region: Ho, Western Region: Sekondi, Western North Region: Sefwi Wiawso.', 'keywords' => 'regions capitals kumasi accra tamale ho'],
  ['category' => 'riddles', 'question' => 'I am a book that helps little kids practice and enhance their writing skills.', 'answer' => 'My first copy book.', 'keywords' => 'riddle copy book writing kids'],
  ['category' => 'riddles', 'question' => 'My name starts with P. I am something Ghana is admired for.', 'answer' => 'Peace.', 'keywords' => 'riddle peace letter p'],
  ['category' => 'sports', 'question' => 'Name all the years Ghana has qualified for the World Cup?', 'answer' => '2006, 2010, 2014, 2022, 2026*', 'keywords' => 'world cup football 2006 2010 2014 2022 2026'],
  ['category' => 'sports', 'question' => 'Female Ghanaian Boxer with world title.', 'answer' => 'Abigail Kwartekaa Quartey (WIBF Super Bantamweight).', 'keywords' => 'boxing abigail kwartekaa quartey wibf'],
  ['category' => 'sports', 'question' => "What are the nicknames of the senior women's team, under 20 and under 17?", 'answer' => 'Black Queens, Black Princesses and Black Maidens respectively.', 'keywords' => 'black queens princesses maidens football women'],
  ['category' => 'sports', 'question' => 'What year did Ghana last host AFCON?', 'answer' => '2008.', 'keywords' => 'afcon 2008 host football'],
  ['category' => 'card_references', 'question' => 'MENTAL', 'answer' => 'A quick fire test math teachers especially used to test memories early in the morning.', 'keywords' => 'mental card reference math test'],
  ['category' => 'card_references', 'question' => 'JULOR', 'answer' => 'Thief in the Ga language.', 'keywords' => 'julor ga thief card reference'],
  ['category' => 'card_references', 'question' => 'DUMSOR', 'answer' => 'An Akan term for "off-on," describing persistent, unpredictable, and intermittent electric power outages.', 'keywords' => 'dumsor power electricity akan outages'],
  ['category' => 'card_references', 'question' => 'CHEW & POUR', 'answer' => 'A Ghanaian idiom for a rote learning strategy where students intensely memorize ("chew") information and immediately regurgitate or write it down ("pour") in an exam, only to promptly forget it afterward.', 'keywords' => 'chew pour rote learning exam'],
  ['category' => 'card_references', 'question' => 'POLICE & THIEF', 'answer' => 'A childhood game where players are grouped into the two teams, and the police go hunting for the thieves.', 'keywords' => 'police thief childhood game'],
  ['category' => 'card_references', 'question' => 'ZANZAMA', 'answer' => 'A childhood game played by multiple people. If you sit down without saying the word, you get knocked.', 'keywords' => 'zanzama childhood game'],
  ['category' => 'card_references', 'question' => 'PILOLO', 'answer' => 'This game was played by hiding sticks in different locations and the players go finding them.', 'keywords' => 'pilolo sticks childhood game'],
  ['category' => 'card_references', 'question' => 'TWO SURE', 'answer' => 'A term used in lottery which means correctly predicting two specific numbers that will appear in the winning set of five numbers.', 'keywords' => 'two sure lottery numbers'],
];
